---
title: "Animation"
author: "Nicole Padlla"
date: "6/30/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
bird_survey<-read.csv("Valley-wide_bird_census_1999-2016.csv")
```


```{r}
library(gganimate)
library(tidyverse)
library(ggplot2)
library(lubridate)

```


```{r}
#add year column
 bird_survey <- bird_survey %>% 
  mutate( year = year(Date))
 # group by species,year add count by year -full data
bird_survey_byyear <- bird_survey %>% 
  group_by(Species, year) %>% 
  summarise(n = n())
```



```{r}
#critical species based on https://www.stateofthebirds.org/2016/resources/species-assessments/
bird_survey_critical <- bird_survey_byyear %>% 
  filter( Species =="EVGR"|Species == "BBCU" |Species=="OSFL"|Species=="BITH"|Species=="WOTH"|Species=="CMWA"|Species =="CAWA")

```



```{r}
#critical birds, change over time
# The palette with black:
cbp2 <- c("#000000", "#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

crit_birdsplot<- ggplot(bird_survey_critical,aes(x=year, y = n, group = Species, color = Species))+
  geom_line()+
  scale_colour_manual(values = cbp2,labels = c("Black_billed Cuckoo", "Bicknell's Thrush ", "Canada Warbler","Cape May Warbler", "Evening Grosbeak","Olive-sided Flycatcher", "Wood Thrush"))+
  labs(title = "Hubbard Brook Experimental Forrest critical bird species", caption = "Data from https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-hbr&identifier=178", x ="", y = "bird count")+
  theme_bw()+
  transition_reveal(year)
crit_birdsplot
anim_save("gganimate_critcial_birds.gif", animation = crit_birdsplot)
```


